apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jarb5o422-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jarb5o422-nodejs 
  name: jarb5o422-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: jarb5o422-nodejs 
